### ISSUE TITLE
How to add support for version 2.3 ?

### ISSUE THREAD

**Issue by abhi18av** [conda-forge/ruby-feedstock#1]
Hi everyone,

Could you tell me how it's possible to add a previous version to a conda-forge recipe?

I'd like to create a environment for `ruby-2.3.3` and `jruby-9.1.12`.

**Comment by scopatz** [comment]
Hi @abhi18av - you can put in a PR to this repo for the previous version of Ruby and it will push out that version.  You can do the same with jruby (if a feedstock exists).

**Comment by abhi18av** [comment]
I've submitted a PR for Ruby-2.3.3 

If there's something that I need to tweak please do guide me :)

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/ruby-feedstock/pull/2 ).
