### ISSUE TITLE
Not possible to use executables provided by gems

### ISSUE THREAD

**Issue by iandol** [conda-forge/ruby-feedstock#132]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Executable gems are broken, what would seem to be a high priority problem for trying to use Ruby installed via conda/mamba/pixi etc. — #116 was closed with an incorrect fix, and the correct fix #130 thanks to @sdruskat (simply link ruby into the rubygems/bin folder properly), is stuck in CI hell. This issue can be closed when #130 is finally merged.

### Installed packages

ε ➪ pixi global list
Global environments as specified in '/Users/ian/.pixi/manifests/pixi-global.toml'
├── eza: 0.20.5 
│   └─ exposes: eza
├── fzf: 0.55.0 
│   └─ exposes: fzf
├── hyperfine: 1.18.0 
│   └─ exposes: hyperfine
├── img2pdf: 0.4.4 
│   └─ exposes: img2pdf, img2pdf-gui
├── jq: 1.7.1 
│   └─ exposes: jq
├── librsvg: 2.58.4 
│   └─ exposes: .librsvg-post-link, rsvg-convert, .librsvg-pre-unlink
├── mosh: 1.4.0 
│   └─ exposes: mosh-server, mosh-client, mosh
├── nvim: 0.10.2 
│   └─ exposes: nvim
├── pandoc: 3.5 
│   └─ exposes: pandoc-lua, pandoc-server, pandoc
├── python 
│   ├─ dependencies: python 3.13.0, setuptools 75.1.0, pip 24.2, pipx 1.7.1
│   └─ exposes: python3.13, python3.1, python3, python, idle3.13, python3.13-config, python3-config, idle3, pydoc, pip, pip3, pipx, pydoc3.13, pydoc3
├── ruby 
│   ├─ dependencies: ruby 3.3.3, compilers 1.8.0
│   └─ exposes: bundle, racc, rake, rdbg, bundler, irb, erb, gem, rbs, rdoc, ri, ruby, syntax_suggest, typeprof
├── sd: 1.0.0 
│   └─ exposes: sd
├── starship: 1.21.1 
│   └─ exposes: starship
├── tmux: 3.5 
│   └─ exposes: tmux
├── typst: 0.12.0 
│   └─ exposes: typst
└── yt-dlp: 2024.10.22 
    └─ exposes: yt-dlp

### Environment info

ε ◎ pixi info
System
------------
      Pixi version: 0.34.0
          Platform: osx-arm64
  Virtual packages: __unix=0=0
                  : __osx=15.1=0
                  : __archspec=1=m2
         Cache dir: /Users/ian/Library/Caches/rattler/cache
      Auth storage: /Users/ian/.rattler/credentials.json
  Config locations: No config files found

Global
------------
           Bin dir: /Users/ian/.pixi/bin
   Environment dir: /Users/ian/.pixi/envs
      Manifest dir: /Users/ian/.pixi/manifests/pixi-global.toml

**Comment by iandol** [comment]
Thank you @wolfv for fixing this in #133 !!!

**Comment by wolfv** [comment]
Thanks for confirming that it works :)
