### ISSUE TITLE
FFI broken on conda-forge, works on conda-forge/label/cf201901

### ISSUE THREAD

**Issue by vbraun** [conda-forge/ruby-feedstock#14]
Issue: Building ffi broke with the recent transition to the gcc7 packages, reverting to cf201901 works

The rbconfig.rb from conda-forge/label/cf201901 contains 
~~~
CONFIG["CC"] = "gcc"
CONFIG["CXX"] = "g++"
~~~
but the new default has
~~~
CONFIG["CC"] = "/home/conda/feedstock_root/build_artifacts/ruby_1537084490905/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc"
CONFIG["CXX"] = "/home/conda/feedstock_root/build_artifacts/ruby_1537084490905/_build_env/bin/x86_64-conda_cos6-linux-gnu-c++"
~~~
Unsurprisingly, trying to build any native gems dies with (/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/ffi-1.10.0/mkmf.log)
~~~
sh: /home/conda/feedstock_root/build_artifacts/ruby_1537084490905/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc: No such file or directory
~~~

**Comment by carterbox** [comment]
I'm having this problem too!

**Comment by jchodera** [comment]
Just wanted to note that I ran into this issue as well, where the compilers listed in `rbconfig.rb` (specifically, in my installation, in`$MINICONDA/lib/ruby/2.4.0/x86_64-darwin14/rbconfig.rb`) were not installed, but editing `rbconfig.rb` manually to contain
```
CONFIG["CC"] = "gcc"
CONFIG["CXX"] = "g++"
```
restored conda-forge installed `ruby`'s`gem install` functionality.

**Comment by phil-blain** [comment]
Relevant pull request: https://github.com/conda-forge/ruby-feedstock/pull/18

**Comment by phil-blain** [comment]
Also, provided we `conda install gcc_linux-64 gxx_linux-64`, the fix provided here https://github.com/ContinuumIO/anaconda-issues/issues/9863#issuecomment-460512146 should work, and according to the conversation there may be preferable for binary compatibility (using the same compilers to build ruby and the gem native extensions).

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/ruby-feedstock/pull/23
