### ISSUE TITLE
2.5.5 Force rebuild is required

### ISSUE THREAD

**Issue by sodre** [conda-forge/ruby-feedstock#26]
Issue:
It looks like the Azure CI did not build the 2.5.5 release. @scopatz, can you manually start the build?
<img width="705" alt="Screen Shot 2019-08-25 at 4 18 54 PM" src="https://user-images.githubusercontent.com/1043285/63655278-2bf27100-c754-11e9-8c0b-0986e26832d8.png">

Thanks

**Comment by scopatz** [comment]
done
