### ISSUE TITLE
MSVC: C++ code that includes ruby.h and uses std::isinf fails because inf is defined as a macro

### ISSUE THREAD

**Issue by traversaro** [conda-forge/ruby-feedstock#47]
When compiling C++ code that includes `ruby/config.h` on Visual Studio and that uses std::isinf, the compilation fails with the error:
~~~
  rubyRUBY_wrap.cxx
C:\src\dome-dev\ign-math\include\ignition/math/Helpers.hh(432): error C2589: '(': illegal token on right side of '::' [C:\src\dome-dev\ign-math\build\src\math.vcxproj]
C:\src\dome-dev\ign-math\include\ignition/math/Helpers.hh(432): error C2062: type 'unknown-type' unexpected [C:\src\dome-dev\ign-math\build\src\math.vcxproj]
C:\src\dome-dev\ign-math\include\ignition/math/Helpers.hh(432): error C2059: syntax error: ')' [C:\src\dome-dev\ign-math\build\src\math.vcxproj]
C:\src\dome-dev\ign-math\include\ignition/math/Helpers.hh(440): error C2589: '(': illegal token on right side of '::' [C:\src\dome-dev\ign-math\build\src\math.vcxproj]
C:\src\dome-dev\ign-math\include\ignition/math/Helpers.hh(440): error C2062: type 'unknown-type' unexpected [C:\src\dome-dev\ign-math\build\src\math.vcxproj]
C:\src\dome-dev\ign-math\include\ignition/math/Helpers.hh(440): error C2059: syntax error: ')' [C:\src\dome-dev\ign-math\build\src\math.vcxproj]
~~~

The error is in the missing.h file of ruby, where isinf is defined as a macro: https://github.com/ruby/ruby/blob/v2_7_2/include/ruby/missing.h#L164 . I need to investigate if this was fixed upstream in the latest version.  

By the way, I recently discovered that when you have this invasive macro bugs on MSVC, and easy way to debug them is to add a line: 
~~~
#define isinf EMIT WARNING C4005
~~~
and this will give you as a warning the location of the code that is defining `isinf`  as a macro.

**Comment by traversaro** [comment]
Upstream fix proposed in https://github.com/ruby/ruby/pull/3758 .

**Comment by wolfv** [comment]
Macro bugs are annoying! Does #undef work in this case?

**Comment by traversaro** [comment]
> Macro bugs are annoying! Does #undef work in this case?

I guess it should work, but avoiding the unnecessary `isinf` macro definition in the first place as done in https://github.com/ruby/ruby/pull/3758 may be more robust.
